### PR TITLE
todolist added

### PR DESCRIPTION
**Pull request by dilashaupadhyay**
### Checklist

- [x] I have tested these changes locally.
- [x] I have added/updated documentation as needed.
- [x] I have reviewed my code for potential issues.
- [x] I have followed the project's coding guidelines.
- [x] I have updated relevant comments and commit messages.

### By submitting this PR, I confirm that

- [x] I have read and understood the project's contributing guidelines.
- [x] This PR is ready for review and merging.
- [x] I understand that automated tests should pass before merging.

### CODE REVIEW

**Comment by ankman007** [comment]
@dilashaupadhyay Please edit this PR description so that all boxes in checklist are actually checked. Other than that its seems all it has passed all the checks for this PR. I will merge it. Thanks.

**Review by ankman007 — APPROVED** [review]
Seems good.

**Comment by manjilkoirala** [comment]
I guess, Description was missing. Although its already merged. Next time you could add description linking the issue also.

**Comment by dilashaupadhyay** [comment]
Closes #29

**Pull request merged**
