### PR TITLE
Magic 8-ball

### PR DESCRIPTION
**Pull request by Prasiddhidahal**
### Description

To add contribution to yantra-lite and I have made a simple magic 8-ball game using web animation . 

### Changes Made

I have added my name folder in participants folder. created html, css, js files for magic 8-balls. Used web Animation api. 

### Checklist

- [x] I have tested these changes locally.
- [x] I have added/updated documentation as needed.
- [x] I have reviewed my code for potential issues.
- [x] I have followed the project's coding guidelines.
- [x] I have updated relevant comments and commit messages.

### Screenshots (if applicable)

magic 8-ball

### Additional Information

I have made a simple magic 8-ball game using web animation and added my name to bootcamp file too. 

### By submitting this PR, I confirm that

- [x] I have read and understood the project's contributing guidelines.
- [x] This PR is ready for review and merging.
- [x] I understand that automated tests should pass before merging.

### CODE REVIEW

**Comment by ankman007** [comment]
@Prasiddhidahal Please add proper description to your issues. Checklist, screenshots & last section your description seem to be incomplete. Other than that everything seems good on my part, it has passed all automated checks. After you've updated description, ping me. I will approve your PR. Thanks.

**Comment by Prasiddhidahal** [comment]
Now, I have added description, Screenshots and checklists .

**Comment by Prasiddhidahal** [comment]
I think it's done now, please review it. Thank you

**Review by manjilkoirala — CHANGES_REQUESTED** [review]
The code seems good, please change your PR title with the appropriate name. You can use the name of the project or the name of the API you have used.

**Comment by Prasiddhidahal** [comment]
Fixed.

**Comment by manjilkoirala** [comment]
> Fixed.

Also you have committed your work in the main branch. It is recommended to change your branch name to feature:implementing-web-animation, then push it.

**Comment by Prasiddhidahal** [comment]
I created a branch called web-animation and pushed. Is it okay now or do I
need to create A new pull request?

**Comment by manjilkoirala** [comment]
@Prasiddhidahal change minor code being in the feature branch then sync that changes. It will reflect in this PR so no need to open another.

**Comment by Prasiddhidahal** [comment]
It's done. Pls review it.

**Review by manjilkoirala — APPROVED** [review]

**Pull request merged**
